### ISSUE TITLE
[android] Cannot restore purchases

### ISSUE THREAD

**Issue by rodydavis** [hymns-for-worship/issues#2]
Running the latest version of the app, purchases will not restore.

**Comment by rodydavis** [comment]
Related: https://github.com/hymns-for-worship/issues/issues/3

**Comment by HughDeLong** [comment]
on Android phone - Android version 12, updated July 5, 2022 - 
Hymns For Worship - 2.1.4+463
Went to LIBRARY  --> Hymnals --> Revised --> Holy,Holy,Holy --> [then tried several options
Sheet Music --- offered the opportunity to purchase! ... tried 'restore purchases' - nothing happens,  tried Purchase and receive error message - you already own this item.

Did the same only instead of the Sheet Music option, tried  SLIDES -- but got the same errors...

**Comment by rodydavis** [comment]
Fix is on the way!
