### ISSUE TITLE
Not able to view sheet music

### ISSUE THREAD

**Issue by jgh450** [hymns-for-worship/issues#32]
I just downloaded the most recent update and can't view the sheet music or hymnals after restoring purchases. The app has been almost totally unusable for the past year or so, I really wish you guys would just somehow revert to the old version of the app. I have been very disappointed with the updates since around 2022.

**Comment by rodydavis** [comment]
There are quite a few issues out of my control relating to the latest versions of iOS and android. 

I’m a solo developer passionate about bringing sheet music to as many people as possible.

when making issues on the repository I do not mind receiving feedback, but keep in mind there is a human aspect to this.

I spent 8 months almost every single day working on the last update. There were some things that didn’t land how I wanted but other things that went super well.

the old version of the app was simpler during COVID and have the access to the hymnals temporarily enabled free for everyone.

I’m still working on fixing the edge cases and most users can install, restore/purchase and view hymnals no problem.

im very sorry you have had a poor experience but it is not because of lack of care.

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this
